card_payment/urls.py
from django.conf.urls import include, url

import charge_card
import tokenize_card
import enquiry

charge_card_urls = [
    url(r'^initiate', charge_card.initiate, name="char_initiate"),
    #url(r'^enter-otp', charge_card.enter_otp, name="char_enter_otp"),
    url(r'^transaction-result', charge_card.transaction_result, name="char_transaction_result"),
]

tokenize_card_urls = [
    url(r'^initiate', tokenize_card.initiate, name="tok_initiate"),
    #url(r'^enter-otp', tokenize_card.enter_otp, name="tok_enter_otp"),
    url(r'^transaction-result', tokenize_card.transaction_result, name="tok_transaction_result"),
]

enquiry_urls = [
        url(r'^initiate', enquiry.initiate_bal_enquiry, name="initiate_bal_enquiry"),
        url(r'^get-available-banks', enquiry.get_available_banks, name="get_available_banks"),
        url(r'^account-enquiry', enquiry.account_enquiry, name="account_enquiry"),
]

urlpatterns = [
    url(r'^charge-card/', include(charge_card_urls)),
    url(r'^tokenize-card/', include(tokenize_card_urls)),
    url(r'^enquiry/', include(enquiry_urls)),
]

django_flutterwave/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from card_payment.general import enter_otp


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^$', TemplateView.as_view(template_name = 'options.html'), name="options"),
    url(r'^enter-otp', enter_otp, name="enter_otp"),
    url(r'^payment/', include('card_payment.urls', namespace="payment")),
]

card_payment/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

card_payment/views.py
from django.shortcuts import render, redirect
from flutterwave import Flutterwave
from django.http import HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.contrib import messages

api_key         = "tk_HhfBSYgKZwid1E8G9yPF"
merchant_key    = "tk_biDdQrtXvO"

def initialize_flw(api_key, merchant_key):    
    flw = Flutterwave(api_key, merchant_key, {"debug": True})
    return flw

def keep_values(request, keys_list, data_dict):
    for key in keys_list:
        request.session[key] = data_dict[key]

def clear_values_from_session(request, keys_list):
    for key in keys_list:
        if request.session.has_key(key):
            del request.session[key]
            
            
def initiate(request):
    '''Verify'''
    
    if request.method == "POST":
        print request.POST
        print 'posting to verify card'
                
        payload = request.POST.copy()
        payload.update({"customerID": "cust1471629671",
                    'responseUrl': reverse('payment:initiate')})
        payload.pop('csrfmiddlewaretoken')
        
        bvn_or_pin = False
        if payload['authModel'] == ('BVN' or 'PIN'):
            bvn_or_pin = True
        
        flw                     = initialize_flw(api_key, merchant_key)
        #print 'data: ',data
        
        verify                  = flw.card.charge(payload)
        verify_json             = verify.json()
        
        print 'verify_json: ',verify_json
        response_data = verify_json['data']
        
        if response_data.has_key('responsemessage'):
            responseMessage         = response_data['responsemessage']
            messages.error(request, '%s' %responseMessage)
        
        if verify_json['status'] != 'error':
            
            response_data.update({'country': payload['country']})
            print 'response_data: ',response_data
            responsecode = response_data['responsecode']
            if responsecode == '02':
                keys_list = ['otptransactionidentifier', 'transactionreference', 'country']
                keep_values(request, keys_list, response_data)
                
                if bvn_or_pin == True:
                    return redirect(reverse('payment:enter_otp'))
        else:
            responseMessage = verify_json['status']
            messages.error(request, '%s' %responseMessage)
            
    months = []
    for i in range(1, 13):
        months.append(str(i).zfill(2))
    
    years = []
    for i in range(6):
        years.append(str(2016+i))
    
    return render(request, 'initiate.html', {'months': months, 'years': years})
    


def enter_otp(request):
    
    if request.method == 'POST':
        data = request.POST.copy()
        
        flw                     = initialize_flw('', '')
        
        verify                  = flw.card.validate(data)
        verify_json             = verify.json()
        
        
    else:
        if request.session.has_key('otptransactionidentifier'):# and request.session.has_key('verifyUsing'):
            context = {'otpTransactionIdentifier': request.session['otptransactionidentifier'],
                       'country': request.session['country']}
            return render(request, 'enter_otp.html', context)
        
        return redirect(reverse('initiate'))

def validation_result(request):
    # context = {}
    # '''Validate BVN'''
    # if request.method == "POST":
    #     otp = request.POST.get('otp')
    #     
    #     '''Retrieve saved values from session'''
    #     api_key, merchant_key, verifyUsing, country, transactionReference, bvn  = retrieve_values(request)           
    #     
    #     flw                                     = initialize_flw(api_key, merchant_key)
    #     validate                                = flw.bvn.validate(bvn, otp, transactionReference, country)
    #     validate_json                           = validate.json()
    #     
    #     print 'validate_json: ',validate_json
    #     
    #     context.update({'data': validate_json['data']})
    #             
    #     # '''Clear saved values from session'''
    #     keys_list = ['api_key', 'merchant_key', 'verifyUsing', 'country', 'transactionReference', 'bvn']
    #     clear_values_from_session(request, keys_list)

        
    return render(request, 'bvn/bvn_verification_result.html', context)
        
    

card_payment/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    {% block page_title %} {% endblock page_title %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
    
    
    
    <style>
      .container{
        position: relative; top: -30px; 
      }
      .vertical-center{
          min-height: 100%;
          min-height: 100vh;
          display: flex;
          align-items: center;
        }
      .row-fluid select { height: 43px !important;}
      
      .row-fluid{
            padding-top: 10px;
        }
        
      .row-fluid.disabled input{
            border-color: green;
            pointer-events: none;
        }
      .form-signin {min-width: 412px;}
      .error{ color: red}
      #modal_header_info{font-size: large}
      .alert-error{
            color: #a94442;
            background-color: #f2dede;
            border-color: #ebccd1;
      }
    </style>
  </head>

  <body>
    
    <!--<div class="jumbotron vertical-center">-->
    <!--<div class="jumbotron">-->
          <div class="container">        
        
              {% block container_content %}
              
              {% endblock container_content %}
              
          </div> <!-- /container -->
    <!--</div>-->
    
    
    {% include 'waiting_for_response_modal.html' %}

      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.validate.js' %}"></script>
    
    {% block script %}
    
    {% endblock script %}
    
    <script>
      
        //source: https://www.abeautifulsite.net/vertically-centering-bootstrap-modals
        $(function(){
          
          function reposition() {
            var modal = $(this),
            dialog = modal.find('.modal-dialog');
            
            modal.css('display', 'block');
            
            // Dividing by two centers the modal exactly, but dividing by three 
            // or four works better for larger screens.
            dialog.css("margin-top", Math.max(0, ($(window).height() - dialog.height()) / 2));
        
          }
          
          //Reposition when a modal is shown
          $('.modal').on('show.bs.modal', reposition);
          
          // Reposition when the window is resized
          $(window).on('resize', function(){
              $('.modal:visible').each(resposition)
          })
        })
      
        $('.btn').click(function(e){
            e.preventDefault();
            
            $form = $(this).closest('form');
            if ($form.valid()) {
                $('#id_verifying').modal('show');
                $form.submit();
            }
           
            
        });
    </script>
      
  </body>
</html>

card_payment/templates/charge_card/initiate.html
{% extends 'base.html' %}    
        
{% block page_title %}
    <title>Flutterwave Card Payment</title>
{% endblock page_title %}

{% block container_content %}
 
<form class="form-signin" method="POST" action="" id="enter_bvn">
{% csrf_token %}

    {% include 'header.html' with header_msg='Charge Card' %}
    
    {% for msg in messages %}
    <div class="alert alert-{{msg.level_tag}}">
      <h5 class="text-center">{{ msg }}</h5>
    </div>
    {% endfor %}
    
    
    <div class="row-fluid">
        <label>Card Number</label>
        <input type="text" name="cardNumber" class="form-control" value="4842508225502547">
    </div>
  
    <div class="row row-fluid">
        <div class="form-group col-xs-4">
            <label>Expiry Month</label>
            <select name="expiryMonth" class="form-control">
                <option value="10">10</option>
                <!--{% for val in months %}
                  <option value="{{ val }}">{{ val }}</option>
                {% endfor %}-->
            </select>
        </div>
        
        <div class="form-group col-xs-4">
            <label>Expiry Year</label>
            <select name="expiryYear" class="form-control">
                <option value="18">18</option>
               <!--{% for val in years %}
                  <option value="{{ val|slice:'2:' }}">{{ val }}</option>
                {% endfor %}-->
            </select>
        </div>
        <div class="form-group col-xs-4">
            <label>CVV2/CVC</label>
            <input type="number" name="cvv" class="form-control" value="136">
        </div>
    </div>
    
    <div class="row row-fluid">
        <div class="form-group col-xs-4">
              <label>Country</label>
              <select name="country" class="form-control" required>
                  <option value="">Select</option>
                  {% for country in countries %}
                  <option value="{{ country.code }}">{{ country.name }}</option>
                  {% endfor %}
              </select>
       </div>
       <div class="form-group col-xs-4">
              <label>Currency</label>
              <select name="currency" class="form-control" required>
                  <option value="">Select</option>
                  {% for currency in currencies %}
                  <option value="{{ currency.code }}">{{ currency.name }}</option>
                  {% endfor %}
              </select>
       </div>
        <div class="form-group col-xs-4">
            <label>Amount</label>
            <input type="number" name="amount" class="form-control" value="2000">
        </div>
    </div>
    
    <div class="row row-fluid">
        <div class="form-group col-xs-4">
          <label>Auth. Method</label>
          <select name="authModel" id="id_authModel" class="form-control" required>
              <option value="">Select Auth Method</option>
              <option value="BVN">BVN</option>
              <option value="PIN">PIN</option>
              <option value="NOAUTH">NOAUTH</option>
              <option value="VBVSECURECODE">VBVSECURECODE</option>
          </select>
       </div>
       
       <div class="form-group col-xs-8 hidden" id="bvn_div">
          <label>BVN Number</label>
          <input type="text" name="bvn" class="form-control" value="12345678901">
       </div>
       
       <div class="form-group col-xs-4 hidden" id="pin_div">
            <label>PIN</label>
            <input type="number" name="pin" class="form-control" value="1111">
        </div>
        
    </div>
  
        
    <div class="row-fluid">
        <label>Transaction Description</label>
        <input type="text" name="narration" class="form-control" value="Card Testing" readonly>
    </div>
    
    <div class="row-fluid" style="padding-top: 20px;">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    </div>
    
    <div class="row-fluid">
      {{ decoded_responsehtml }}
    </div>
    
</form>

{% endblock container_content %}


{% block script %}
  <script>
    $('#id_authModel').on('change', function(){
        var optionSelected = $('option:selected', this);
        var option_val = optionSelected.val();
        if (option_val == 'PIN') {
            $('#pin_div').removeClass('hidden');
            $('#bvn_div').addClass('hidden');
        }else if(option_val == 'BVN'){
            $('#pin_div').addClass('hidden');
            $('#bvn_div').removeClass('hidden');
        }else{
            $('#pin_div').addClass('hidden');
            $('#bvn_div').addClass('hidden');
        }
    })
  </script>
{% endblock %}

card_payment/templates/enquiry/account_enquiry.html
{% extends 'base.html' %}    
        
{% block page_title %}
    <title>Flutterwave Card Payment - Enter OTP</title>
{% endblock page_title %}

{% block container_content %}
<form class="form-signin"  method="POST" action="">
{% csrf_token %}
  
    <!--<h3 class="form-signin-heading text-center"></h3>-->
        
    {% include 'header.html' with header_msg='Account Enquiry' header_msg_2='Please enter the account number you want to verify its information' %}

    {% for msg in messages %}
    <div class="alert alert-danger">
      <h5 class="text-center">{{ msg }}</h5>
    </div>
    {% endfor %}

    <div class="row-fluid">
      <label>Bank</label>
      <select name="destBankCode" class="form-control">
        {% for key, val in data %}
          <option value="{{ key }}">{{ val }}</option>
        {% endfor %}
      </select>
    </div>
    
    <div class="row-fluid">
        <label>Account Number</label>
        <input type="number" name="recipientAccount" class="form-control" autofocus>
    </div>

    <div class="row-fluid">
        <label>Country</label>
        <select name="country" class="form-control">
            <option value="NG">Nigeria</option>
            <option value="US">United States</option>
            <option value="UK">United Kingdom</option>
        </select>
    </div>
    
    <div class="row-fluid" style="padding-top: 40px;">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    </div>
  

</form>

<div class="row-fluid text-center">      
      <a href="{% url 'options' %}"><h5>Try Another Transaction</h5></a>
</div>
{% endblock container_content %}

{% block script %}
  
{% endblock %}

card_payment/templates/enquiry/initiate.html
{% extends 'base.html' %}    
        
{% block page_title %}
    <title>Flutterwave Card Payment</title>
{% endblock page_title %}

{% block container_content %}
 
<form class="form-signin" method="POST" action="" id="enter_bvn">
{% csrf_token %}

    {% include 'header.html' with header_msg='Card Balance Enquiry' %}
    
    {% for msg in messages %}
    <div class="alert alert-{{ msg.level_tag }}">
      <h5 class="text-center">{{ msg }}</h5>
    </div>
    {% endfor %}
    
    
    <div class="row-fluid">
        <label>Card Number</label>
        <input type="text" name="cardNumber" class="form-control" value="4842508225502547">
    </div>
  
    <div class="row row-fluid">
        <div class="form-group col-xs-4">
            <label>Expiry Month</label>
            <select name="expiryMonth" class="form-control">
                <!--<option value="10">10</option>-->
                {% for val in months %}
                  <option value="{{ val }}">{{ val }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div class="form-group col-xs-4">
            <label>Expiry Year</label>
            <select name="expiryYear" class="form-control">
                <!--<option value="18">18</option>-->
               {% for val in years %}
                  <option value="{{ val|slice:'2:' }}">{{ val }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group col-xs-4">
            <label>CVV2/CVC</label>
            <input type="number" name="cvv" class="form-control" value="136">
        </div>
    </div>
    
    <div class="row row-fluid">
        
        <div class="form-group col-xs-6">
            <label>PIN</label>
            <input type="number" name="pin" class="form-control" value="1111">
        </div>
        
        <div class="form-group col-xs-6">
            <label>Country</label>
            <select name="country" class="form-control" required>
                <option value="">Select</option>
                {% for country in countries %}
                  <option value="{{ country.code }}">{{ country.name }}</option>
                {% endfor %}
                <!--<option value="NG">Nigeria</option>
                <option value="US">United States</option>
                <option value="UK">United Kingdom</option>-->
            </select>
       </div>
       
    </div>
    
    <div class="row-fluid">
        <label>Transaction Reference</label>
        <input type="text" name="transactionRef" class="form-control" value="{{ transactionRef }}" readonly>
    </div>
    
    <div class="row-fluid" style="padding-top: 20px;">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    </div>
    
</form>

{% endblock container_content %}

 
  

card_payment/templates/enter_otp.html
{% extends 'base.html' %}    
        
{% block page_title %}
    <title>Flutterwave Card Payment - Enter OTP</title>
{% endblock page_title %}

{% block container_content %}
<form class="form-signin"  method="POST" action="{% url 'payment:char_transaction_result' %}">
{% csrf_token %}
  
    <h3 class="form-signin-heading text-center">Enter One Time Password (OTP)</h3>
    
    <h5 class="text-center">Please enter the OTP that was sent/given to you via telephone</h5>
    
    {% for msg in messages %}
    <div class="alert alert-danger">
      <h5 class="text-center">{{ msg }}</h5>
    </div>
    {% endfor %}

    <div class="alert alert-success hidden" id="alert_div">
      <h5 class="text-center" id="resend_otp_info"></h5>
    </div>
    
    <!--<h5 class="text-success text-center" id="resend_otp_info"></h5>-->
    
    <div class="row-fluid">
        <label>Transaction Identifier</label>
        <input type="text" name="otpTransactionIdentifier" class="form-control" value="{{ otpTransactionIdentifier }}" readonly>
    </div>
    
    <div class="row-fluid">
        <label>Country</label>
        <input type="text" name="country" class="form-control" value="{{ country }}" readonly>
    </div>
    
    <div class="row-fluid">
        <label>OTP</label>
        <input type="text" name="otp" id="id_otp" class="form-control" required autofocus>
    </div>
    
    
    <div class="row-fluid" style="padding-top: 40px;">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    </div>
  

</form>

<div class="row-fluid text-center">
      <!--<a href="#" id="resend_otp"><h5>Resend OTP</h5></a> </br>-->
      
      <a href="{% url 'payment:char_initiate' %}"><h5>Try Another Transaction</h5></a>
</div>
{% endblock container_content %}

{% block script %}
  <script>
    $("#resend_otp").click(function(){
      $('#id_verifying').find('#modal_header_info').html('Re-sending OTP. Please wait...');
      $('#id_verifying').modal('show');
      
      $.ajax({
        url: "",
        method: 'GET',
        
        success: function(data){
          if (data.status == 'success'){
            
            $('#resend_otp_info').html('OTP Re-Sent Successfully. Please check your phone.');
            $('alert_div').removeClass('hidden')
             
             //$modal_header_info = $('#id_verifying').find('#modal_header_info');
             // $modal_header_info.html('')
             // $modal_header_info.html('<h5>Re-sending OTP. Please wait...</h5>')
             // 
            $('#id_verifying').modal('hide');
          }
          
        }
      })
      
    });
    
  </script>
{% endblock %}

card_payment/templates/header.html
{% load staticfiles %}
<div class="row text-center" style="padding-bottom: 30px;">
    <a href="{% url 'options' %}"><img src="{% static 'img/flutt.min.png' %}" style="height: 50px;"/></a>
      <h3 class="form-signin-heading">
        {{ header_msg }}
      </h3>
    {% if header_msg_2 %}
    <h5 class="text-center">{{ header_msg_2 }}</h5>
    {% endif %}

</div>

card_payment/templates/initiate.html
{% extends 'base.html' %}    
        
{% block page_title %}
    <title>Flutterwave Card Payment</title>
{% endblock page_title %}

{% block container_content %}
 
<form class="form-signin" method="POST" action="" id="enter_bvn">
{% csrf_token %}

    <h3 class="form-signin-heading text-center">Flutterwave Card Payment</h3>
    
    {% for msg in messages %}
    <div class="alert alert-danger">
      <h5 class="text-center">{{ msg }}</h5>
    </div>
    {% endfor %}
    
    
    <div class="row-fluid">
        <label>Card Number</label>
        <input type="text" name="cardNumber" class="form-control" value="4842508225502547">
    </div>
  
    <div class="row row-fluid">
        <div class="form-group col-xs-4">
            <label>Expiry Month</label>
            <select name="expiryMonth" class="form-control">
                <option value="10">10</option>
                <!--{% for val in months %}
                  <option value="{{ val }}">{{ val }}</option>
                {% endfor %}-->
            </select>
        </div>
        
        <div class="form-group col-xs-4">
            <label>Expiry Year</label>
            <select name="expiryYear" class="form-control">
                <option value="18">18</option>
               <!--{% for val in years %}
                  <option value="{{ val|slice:'2:' }}">{{ val }}</option>
                {% endfor %}-->
            </select>
        </div>
        <div class="form-group col-xs-4">
            <label>CVV2/CVC</label>
            <input type="number" name="cvv" class="form-control" value="136">
        </div>
    </div>
    
    <div class="row row-fluid">
        <div class="form-group col-xs-4">
              <label>Country</label>
              <select name="country" class="form-control">
                  <option value="NGN">Nigeria</option>
                  <option value="US">United States</option>
                  <option value="UK">United Kingdom</option>
              </select>
       </div>
       <div class="form-group col-xs-4">
              <label>Currency</label>
              <select name="currency" class="form-control">
                  <option value="NGN">Naira</option>
                  <option value="USD">Dollars</option>
                  <option value="GBP">Pounds</option>
              </select>
       </div>
        <div class="form-group col-xs-4">
            <label>Amount</label>
            <input type="number" name="amount" class="form-control" value="2000">
        </div>
    </div>
    
    <div class="row row-fluid">
        <div class="form-group col-xs-4">
          <label>Auth. Method</label>
          <select name="authModel" class="form-control">
              <option value="BVN">BVN</option>
              <option value="PIN">PIN</option>
              <option value="NOAUTH">NOAUTH</option>
              <option value="VBVSECURECODE">VBVSECURECODE</option>
          </select>
       </div>
       <div class="form-group col-xs-8">
          <label>BVN Number</label>
          <input type="text" name="bvn" class="form-control" value="12345678901">
       </div>
        
    </div>
  
        
    <div class="row-fluid">
        <label>Transaction Description</label>
        <input type="text" name="narration" class="form-control" value="Card Testing" readonly>
    </div>
    
    <div class="row-fluid" style="padding-top: 20px;">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    </div>
    
</form>

{% endblock container_content %}

 
  

card_payment/templates/options.html
{% extends 'base.html' %}
{% load staticfiles %}
        
{% block page_title %}
    <title>Flutterwave Card Payment - Select Option</title>
{% endblock page_title %}

{% block container_content %}
<form class="form-signin"  method="POST" action="">
{% csrf_token %}
  
        {% include 'header.html' with header_msg='Flutterwave Transaction Options'%}
        
        <div class="row-fluid text-center">
              <a href="{% url 'payment:tok_initiate' %}"><h4>Tokenize Card</h4></a>
        </div>
  
        <div class="row-fluid text-center">
              <a href="{% url 'payment:char_initiate' %}"><h4>Charge Card</h4></a>
        </div>
        
        <div class="row-fluid text-center">
            <a href="{% url 'payment:initiate_bal_enquiry' %}"><h4>Check Card Balance</h4></a>
        </div>
        
        <div class="row-fluid text-center">
            <a href="{% url 'payment:get_available_banks' %}"><h4>Show Available Banks</h4></a>
        </div>
        
        <div class="row-fluid text-center">
            <a href="{% url 'payment:account_enquiry' %}"><h4>Account Enquiry</h4></a>
        </div>

</form>
{% endblock container_content %}

 

card_payment/templates/result.html
{% extends 'base.html' %}    
        
{% block page_title %}
    <title>Flutterwave Card Payment - Transaction Result</title>
{% endblock page_title %}

{% block container_content %}
<form class="form-signin"  method="POST" action="">
{% csrf_token %}
  
      <!--<div class="row text-center" style="padding-bottom: 30px;">
          <h3 class="form-signin-heading">Transaction/Enquiry Result</h3>
          <h5 class="text-success">Please find below the result of your transaction/enquiry</h5>
      </div>-->
      
      {% include 'header.html' with header_msg='Transaction/Enquiry Result' header_msg_2='Please find below the result of your transaction/enquiry' %}
      
      <div class="table-responsive">
            <table class="table table-bordered">
                {% if charge_card or tokenize_card %}
                    {% if data.transactionreference %}
                    <tr>
                      <td>Transaction Reference</td>
                      <td>{{ data.transactionreference }}</td>
                    </tr>
                    {% endif %}
                    <tr>
                      <td>Response Token</td>
                      <td>{{ data.responsetoken }}</td>
                    </tr>
                    
                    <tr>
                      <td>Response Message</td>
                      <td>{{ data.responsemessage }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td>S/N</td>
                        <td>Bank</td>
                        <td>Bank Code</td>
                    </tr>
                    {% for key,val in data %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ val }}</td>
                        <td>{{ key }}</td>
                    </tr>
                    {% endfor %}
                {% endif %}
                  
            </table>
      </div>
      
      <div class="row-fluid text-center">
            <a href="{% url 'options' %}"><h5>Return to Homepage</h5></a>
      </div>

</form>
{% endblock container_content %}

 

card_payment/templates/waiting_for_response_modal.html
{% load static %}

<!-- Modal -->
<div id="id_verifying" data-backdrop="static" data-keyboard="false" tabindex="-1" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <!--<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"></h4>
      </div>-->
      <div class="modal-body" style="text-align: center;">
        <p id="modal_header_info">Verifying Card Information. Please wait...</p>
        
        <img src="{% static 'img/ring-alt.gif' %}"
      </div>
      
      <!--<div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>-->
    </div>

  </div>
</div>